spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - https://projectname.example.com
              - https://projectname.azure.example.com
      routes:
        - id: config
          uri: https://projectname-nam.example.com
          predicates:
            - Path=/api/config/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: actuator-health
          uri: http://localhost:8081
          predicates:
            - Path=/actuator/health
            - Method=GET
        - id: change-request-service
          uri: http://change-request-service:8080
          predicates:
            - Path=/api/change-request-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: projectname-configuration-service
          uri: http://projectname-configuration-service:8080
          predicates:
            - Path=/api/configuration-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: projectname-ui
          uri: http://projectname-frontend:8080
          predicates:
            - Path=/**
  security:
    oauth2:
      client:
        provider:
          nam:
            issuer-uri: https://idp.example.com/nidp/oauth/nam
            authorization-uri: https://idp.example.com/nidp/oauth/nam/authz?resourceServer=mirai
            token-uri: https://idp.example.com/nidp/oauth/nam/token?resourceServer=mirai
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/nidp/oauth/nam
          jwk-set-uri: https://idp.example.com/nidp/oauth/nam/keys
          jws-algorithm: RS512
