spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - https://projectname-tst.example.com
              - https://projectname-tst.azure.example.com
              - http://localhost:4200
      routes:
        - id: config
          uri: https://projectname-tst-nam.example.com
          predicates:
            - Path=/api/config/v0.1/**
          filters:
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: actuator-health
          uri: http://localhost:8081
          predicates:
            - Path=/actuator/health
            - Method=GET
        - id: change-request-service
          uri: http://change-request-service:8080
          predicates:
            - Path=/api/change-request-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: projectname-configuration-service
          uri: http://projectname-configuration-service:8080
          predicates:
            - Path=/api/configuration-service/**
          filters:
            - StripPrefix=2
            - SetResponseHeader=Content-Type, application/json
            - TokenRelay
        - id: projectname-ui
          uri: http://projectname-frontend:8080
          predicates:
            - Path=/**
